import type { Template } from '../templates/types';

export function defaultTemplate(overrides: Partial<Template> = {}): Template {
  return {
    logo_url: '',
    from_label: 'From',
    customer_label: 'Bill to',
    invoice_no_label: 'Invoice',
    issue_date_label: 'Issued',
    due_date_label: 'Due',
    amount_due_label: 'Amount due',
    date_format: 'MMM d, yyyy',
    payment_label: 'Payment',
    note_label: 'Notes',
    terms_label: 'Terms',
    description_label: 'Description',
    quantity_label: 'Qty',
    price_label: 'Price',
    total_label: 'Total',
    total_summary_label: 'Total',
    subtotal_label: 'Subtotal',
    subtotal: 0,
    tax_label: 'Tax',
    vat_label: 'VAT',
    tax_rate: 0,
    vat_rate: 0,
    locale: 'en-US',
    timezone: 'UTC',
    include_decimals: true,
    include_units: false,
    include_qr: true,
    include_vat: false,
    include_tax: false,
    include_discount: false,
    discount_label: 'Discount',
    title: 'Invoice',
    ...overrides,
  };
}
