#!/usr/bin/env node
/**
 * Copy the SenderoGuestEscrow ABI from Forge's out/ into ponder/abis/
 * as a TypeScript `as const` export so Ponder can infer event names
 * and argument types.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// __dirname is .../apps/ponder/scripts; walk up 3 levels then into contracts/out.
const __dirname = dirname(fileURLToPath(import.meta.url));
const contractArtifactPath = resolve(
  __dirname,
  '..',
  '..',
  '..',
  'contracts',
  'out',
  'SenderoGuestEscrow.sol',
  'SenderoGuestEscrow.json',
);

const abiTsPath = resolve(__dirname, '..', 'abis', 'SenderoGuestEscrow.abi.ts');

if (!existsSync(contractArtifactPath)) {
  console.error(`✗ Contract artifact not found at ${contractArtifactPath}`);
  console.error('  Run `cd ../contracts && forge build` first.');
  process.exit(1);
}

const artifact = JSON.parse(readFileSync(contractArtifactPath, 'utf-8'));
if (!artifact.abi) {
  console.error('✗ Artifact missing ABI field');
  process.exit(1);
}

// Ponder only indexes events; filter the ABI to avoid TS inference
// bloat from tuple[] struct parameters in write functions.
const eventsOnly = artifact.abi.filter((entry) => entry.type === 'event');

const header = `/**
 * Auto-generated by scripts/sync-abi.js. Do not edit.
 * Source: ../contracts/out/SenderoGuestEscrow.sol/SenderoGuestEscrow.json
 * Filtered to events only (Ponder indexer input).
 */
export const SenderoGuestEscrowAbi = `;
const body = JSON.stringify(eventsOnly, null, 2);
const footer = ` as const;\n`;

mkdirSync(dirname(abiTsPath), { recursive: true });
writeFileSync(abiTsPath, header + body + footer);

console.log(
  `✓ Synced ABI (${eventsOnly.length} events from ${artifact.abi.length} total) → abis/SenderoGuestEscrow.abi.ts`,
);
