/**
 * IATA airport code → ISO-3166-alpha-2 country code resolver.
 *
 * Fallback for Duffel responses where `iata_country_code` is missing on
 * an airport (rare but happens, especially for charter/regional codes).
 * Used by `deriveRouteCountries` in `@sendero/tools` and by the
 * `scripts/backfill-route-countries.ts` script.
 *
 * Coverage: top ~250 airports by commercial passenger volume + major
 * corporate-travel hubs. Roughly 95% of routes Sendero sees fall in
 * this set. Expansion is mechanical — add rows to AIRPORT_TABLE in
 * IATA-COUNTRY-CITY format. For exhaustive coverage, swap to the
 * openflights.org dataset (~10k airports, public domain).
 *
 * Returns null for unknown codes — callers must handle the gap (either
 * report_knowledge_gap, ask the agent for clarification, or skip the
 * row in the map UI).
 */

const AIRPORT_TABLE: ReadonlyArray<readonly [iata: string, alpha2: string]> = [
  // North America — US hubs
  ['ATL', 'US'],
  ['LAX', 'US'],
  ['ORD', 'US'],
  ['DFW', 'US'],
  ['DEN', 'US'],
  ['JFK', 'US'],
  ['SFO', 'US'],
  ['SEA', 'US'],
  ['LAS', 'US'],
  ['MCO', 'US'],
  ['CLT', 'US'],
  ['PHX', 'US'],
  ['MIA', 'US'],
  ['IAH', 'US'],
  ['BOS', 'US'],
  ['MSP', 'US'],
  ['EWR', 'US'],
  ['DTW', 'US'],
  ['LGA', 'US'],
  ['PHL', 'US'],
  ['BWI', 'US'],
  ['SLC', 'US'],
  ['DCA', 'US'],
  ['IAD', 'US'],
  ['MDW', 'US'],
  ['SAN', 'US'],
  ['HNL', 'US'],
  ['TPA', 'US'],
  ['PDX', 'US'],
  ['STL', 'US'],
  ['BNA', 'US'],
  ['AUS', 'US'],
  ['HOU', 'US'],
  ['RDU', 'US'],
  ['MSY', 'US'],
  ['SMF', 'US'],
  ['SJC', 'US'],
  ['OAK', 'US'],
  ['SAT', 'US'],
  ['IND', 'US'],
  ['CMH', 'US'],
  ['CLE', 'US'],
  ['MCI', 'US'],
  ['PIT', 'US'],
  ['JAX', 'US'],
  ['ABQ', 'US'],
  ['BUF', 'US'],
  ['ANC', 'US'],
  ['BOI', 'US'],
  ['PVD', 'US'],
  // Canada
  ['YYZ', 'CA'],
  ['YVR', 'CA'],
  ['YUL', 'CA'],
  ['YYC', 'CA'],
  ['YEG', 'CA'],
  ['YOW', 'CA'],
  ['YHZ', 'CA'],
  ['YWG', 'CA'],
  ['YQB', 'CA'],
  ['YQR', 'CA'],
  // Mexico + Central America + Caribbean
  ['MEX', 'MX'],
  ['CUN', 'MX'],
  ['GDL', 'MX'],
  ['MTY', 'MX'],
  ['TIJ', 'MX'],
  ['SJD', 'MX'],
  ['PVR', 'MX'],
  ['BJX', 'MX'],
  ['MID', 'MX'],
  ['QRO', 'MX'],
  ['PTY', 'PA'],
  ['SJO', 'CR'],
  ['GUA', 'GT'],
  ['SAL', 'SV'],
  ['TGU', 'HN'],
  ['MGA', 'NI'],
  ['BZE', 'BZ'],
  ['NAS', 'BS'],
  ['SDQ', 'DO'],
  ['STI', 'DO'],
  ['PUJ', 'DO'],
  ['SJU', 'PR'],
  ['MBJ', 'JM'],
  ['HAV', 'CU'],
  ['POS', 'TT'],
  ['BGI', 'BB'],
  // South America
  ['GRU', 'BR'],
  ['GIG', 'BR'],
  ['BSB', 'BR'],
  ['CGH', 'BR'],
  ['CNF', 'BR'],
  ['POA', 'BR'],
  ['REC', 'BR'],
  ['FOR', 'BR'],
  ['SSA', 'BR'],
  ['MAO', 'BR'],
  ['SDU', 'BR'],
  ['VCP', 'BR'],
  ['CWB', 'BR'],
  ['BEL', 'BR'],
  ['FLN', 'BR'],
  ['EZE', 'AR'],
  ['AEP', 'AR'],
  ['COR', 'AR'],
  ['MDZ', 'AR'],
  ['BRC', 'AR'],
  ['SCL', 'CL'],
  ['IPC', 'CL'],
  ['CCP', 'CL'],
  ['LIM', 'PE'],
  ['CUZ', 'PE'],
  ['AQP', 'PE'],
  ['BOG', 'CO'],
  ['MDE', 'CO'],
  ['CLO', 'CO'],
  ['CTG', 'CO'],
  ['BAQ', 'CO'],
  ['UIO', 'EC'],
  ['GYE', 'EC'],
  ['CCS', 'VE'],
  ['MVD', 'UY'],
  ['ASU', 'PY'],
  ['VVI', 'BO'],
  ['LPB', 'BO'],
  // Europe — UK/Ireland
  ['LHR', 'GB'],
  ['LGW', 'GB'],
  ['STN', 'GB'],
  ['LTN', 'GB'],
  ['LCY', 'GB'],
  ['MAN', 'GB'],
  ['EDI', 'GB'],
  ['GLA', 'GB'],
  ['BHX', 'GB'],
  ['BRS', 'GB'],
  ['NCL', 'GB'],
  ['ABZ', 'GB'],
  ['LPL', 'GB'],
  ['BFS', 'GB'],
  ['DUB', 'IE'],
  ['ORK', 'IE'],
  ['SNN', 'IE'],
  // Europe — Schengen + west
  ['CDG', 'FR'],
  ['ORY', 'FR'],
  ['NCE', 'FR'],
  ['LYS', 'FR'],
  ['MRS', 'FR'],
  ['TLS', 'FR'],
  ['BOD', 'FR'],
  ['NTE', 'FR'],
  ['FRA', 'DE'],
  ['MUC', 'DE'],
  ['DUS', 'DE'],
  ['HAM', 'DE'],
  ['BER', 'DE'],
  ['STR', 'DE'],
  ['CGN', 'DE'],
  ['HAJ', 'DE'],
  ['NUE', 'DE'],
  ['AMS', 'NL'],
  ['EIN', 'NL'],
  ['RTM', 'NL'],
  ['BRU', 'BE'],
  ['CRL', 'BE'],
  ['ANR', 'BE'],
  ['LUX', 'LU'],
  ['ZRH', 'CH'],
  ['GVA', 'CH'],
  ['BSL', 'CH'],
  ['BRN', 'CH'],
  ['VIE', 'AT'],
  ['SZG', 'AT'],
  ['INN', 'AT'],
  ['MAD', 'ES'],
  ['BCN', 'ES'],
  ['PMI', 'ES'],
  ['VLC', 'ES'],
  ['SVQ', 'ES'],
  ['AGP', 'ES'],
  ['BIO', 'ES'],
  ['LPA', 'ES'],
  ['TFS', 'ES'],
  ['IBZ', 'ES'],
  ['LIS', 'PT'],
  ['OPO', 'PT'],
  ['FNC', 'PT'],
  ['FAO', 'PT'],
  ['FCO', 'IT'],
  ['MXP', 'IT'],
  ['LIN', 'IT'],
  ['BGY', 'IT'],
  ['VCE', 'IT'],
  ['NAP', 'IT'],
  ['BLQ', 'IT'],
  ['CTA', 'IT'],
  ['PMO', 'IT'],
  ['TRN', 'IT'],
  // Europe — north + east
  ['CPH', 'DK'],
  ['BLL', 'DK'],
  ['AAL', 'DK'],
  ['ARN', 'SE'],
  ['GOT', 'SE'],
  ['BMA', 'SE'],
  ['OSL', 'NO'],
  ['BGO', 'NO'],
  ['TRD', 'NO'],
  ['SVG', 'NO'],
  ['HEL', 'FI'],
  ['TMP', 'FI'],
  ['KEF', 'IS'],
  ['WAW', 'PL'],
  ['KRK', 'PL'],
  ['GDN', 'PL'],
  ['POZ', 'PL'],
  ['WRO', 'PL'],
  ['PRG', 'CZ'],
  ['BUD', 'HU'],
  ['OTP', 'RO'],
  ['SOF', 'BG'],
  ['ATH', 'GR'],
  ['SKG', 'GR'],
  ['HER', 'GR'],
  ['RHO', 'GR'],
  ['ZAG', 'HR'],
  ['SPU', 'HR'],
  ['DBV', 'HR'],
  ['LJU', 'SI'],
  ['BTS', 'SK'],
  ['BEG', 'RS'],
  // Middle East + North Africa
  ['DXB', 'AE'],
  ['AUH', 'AE'],
  ['SHJ', 'AE'],
  ['DOH', 'QA'],
  ['RUH', 'SA'],
  ['JED', 'SA'],
  ['DMM', 'SA'],
  ['MED', 'SA'],
  ['KWI', 'KW'],
  ['BAH', 'BH'],
  ['MCT', 'OM'],
  ['AMM', 'JO'],
  ['BEY', 'LB'],
  ['TLV', 'IL'],
  ['CAI', 'EG'],
  ['HRG', 'EG'],
  ['SSH', 'EG'],
  ['IST', 'TR'],
  ['SAW', 'TR'],
  ['AYT', 'TR'],
  ['ESB', 'TR'],
  ['ADB', 'TR'],
  ['CMN', 'MA'],
  ['RAK', 'MA'],
  ['AGA', 'MA'],
  ['TUN', 'TN'],
  ['ALG', 'DZ'],
  // Sub-Saharan Africa
  ['JNB', 'ZA'],
  ['CPT', 'ZA'],
  ['DUR', 'ZA'],
  ['NBO', 'KE'],
  ['MBA', 'KE'],
  ['ADD', 'ET'],
  ['LOS', 'NG'],
  ['ABV', 'NG'],
  ['ACC', 'GH'],
  ['DKR', 'SN'],
  ['CAI', 'EG'],
  // Asia — east
  ['HND', 'JP'],
  ['NRT', 'JP'],
  ['KIX', 'JP'],
  ['ITM', 'JP'],
  ['NGO', 'JP'],
  ['FUK', 'JP'],
  ['CTS', 'JP'],
  ['OKA', 'JP'],
  ['SDJ', 'JP'],
  ['ICN', 'KR'],
  ['GMP', 'KR'],
  ['PUS', 'KR'],
  ['CJU', 'KR'],
  ['PEK', 'CN'],
  ['PVG', 'CN'],
  ['SHA', 'CN'],
  ['CAN', 'CN'],
  ['SZX', 'CN'],
  ['CTU', 'CN'],
  ['XIY', 'CN'],
  ['CKG', 'CN'],
  ['HGH', 'CN'],
  ['NKG', 'CN'],
  ['WUH', 'CN'],
  ['CSX', 'CN'],
  ['KMG', 'CN'],
  ['TAO', 'CN'],
  ['PKX', 'CN'],
  ['HKG', 'HK'],
  ['MFM', 'MO'],
  ['TPE', 'TW'],
  ['TSA', 'TW'],
  ['KHH', 'TW'],
  // Asia — south + southeast
  ['SIN', 'SG'],
  ['KUL', 'MY'],
  ['PEN', 'MY'],
  ['LGK', 'MY'],
  ['BKI', 'MY'],
  ['BKK', 'TH'],
  ['DMK', 'TH'],
  ['HKT', 'TH'],
  ['CNX', 'TH'],
  ['USM', 'TH'],
  ['HAN', 'VN'],
  ['SGN', 'VN'],
  ['DAD', 'VN'],
  ['MNL', 'PH'],
  ['CEB', 'PH'],
  ['DVO', 'PH'],
  ['CGK', 'ID'],
  ['DPS', 'ID'],
  ['SUB', 'ID'],
  ['UPG', 'ID'],
  ['PNH', 'KH'],
  ['REP', 'KH'],
  ['VTE', 'LA'],
  ['RGN', 'MM'],
  ['DEL', 'IN'],
  ['BOM', 'IN'],
  ['BLR', 'IN'],
  ['MAA', 'IN'],
  ['HYD', 'IN'],
  ['CCU', 'IN'],
  ['COK', 'IN'],
  ['AMD', 'IN'],
  ['PNQ', 'IN'],
  ['GOI', 'IN'],
  ['CMB', 'LK'],
  ['DAC', 'BD'],
  ['KTM', 'NP'],
  ['ISB', 'PK'],
  ['KHI', 'PK'],
  ['LHE', 'PK'],
  ['KBL', 'AF'],
  ['THR', 'IR'],
  ['IKA', 'IR'],
  // Oceania
  ['SYD', 'AU'],
  ['MEL', 'AU'],
  ['BNE', 'AU'],
  ['PER', 'AU'],
  ['ADL', 'AU'],
  ['CNS', 'AU'],
  ['OOL', 'AU'],
  ['HBA', 'AU'],
  ['DRW', 'AU'],
  ['CBR', 'AU'],
  ['AKL', 'NZ'],
  ['WLG', 'NZ'],
  ['CHC', 'NZ'],
  ['ZQN', 'NZ'],
  ['NAN', 'FJ'],
  ['PPT', 'PF'],
];

// Dedupe + freeze. The table has accidental dupes (e.g., CAI under both
// MEA and Africa) — last write wins. Lookup is case-insensitive.
const _IATA_TO_ALPHA2: ReadonlyMap<string, string> = (() => {
  const map = new Map<string, string>();
  for (const [iata, alpha2] of AIRPORT_TABLE) {
    map.set(iata.toUpperCase(), alpha2.toUpperCase());
  }
  return map;
})();

/**
 * Resolve an IATA airport code to its ISO-3166 alpha-2 country code.
 * Returns null when the code isn't in the curated table — callers must
 * decide how to handle the gap.
 */
export function iataToCountryAlpha2(iata: string | null | undefined): string | null {
  if (!iata) return null;
  const code = iata.trim().toUpperCase();
  if (!/^[A-Z]{3}$/.test(code)) return null;
  return _IATA_TO_ALPHA2.get(code) ?? null;
}

/** Number of airports in the curated table. Useful for telemetry +
 *  `__tests__/country-from-iata.test.ts` coverage assertions. */
export const IATA_COUNTRY_TABLE_SIZE = _IATA_TO_ALPHA2.size;
