/**
 * Pure rendering helpers for the gap-scanner CLI.
 *
 * Lives separately from `scan-knowledge-gaps.ts` so unit tests can
 * import the bucketing + markdown logic without pulling in the
 * `@sendero/database` dep (which is a peer of the workspace and not
 * resolvable from the scripts directory at test time).
 *
 * The shape of `KnowledgeGapRow` deliberately mirrors the Prisma row
 * type so the CLI can pass rows straight through. We avoid importing
 * the Prisma type here on purpose — that's the dep we're insulating
 * tests from.
 */

export interface KnowledgeGapRow {
  id: string;
  tenantId: string;
  traceId: string | null;
  kind:
    | 'tool_input_mismatch'
    | 'tool_not_found'
    | 'tool_error_unrecoverable'
    | 'instruction_missing'
    | 'env_missing'
    | 'schema_drift'
    | 'runtime_constraint'
    | 'other';
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'triaged' | 'in_progress' | 'resolved' | 'duplicate' | 'wontfix';
  toolName: string | null;
  errorMessage: string;
  hypothesis: string;
  suggestedFix: string | null;
  blockingTraveler: boolean;
  channelKind: string | null;
  surface: string | null;
  resolvedAt: Date | null;
  resolutionNote: string | null;
  resolutionPrUrl: string | null;
  occurrenceCount: number;
  firstSeenAt: Date;
  lastSeenAt: Date;
}

export type Bucket = 'critical' | 'high' | 'medium' | 'low';

/**
 * Bucket recomputed at scan time so a "low" row that has now fired
 * 50 times escalates without us racing the upsert path. Truth is in
 * the row + its history; severity column is just a hint.
 */
export function bucket(gap: KnowledgeGapRow): Bucket {
  if (gap.severity === 'critical') return 'critical';
  if (gap.severity === 'high') return 'high';
  // Repeat-offender promotion: 3+ occurrences of a blocking gap
  // warrants escalation regardless of original severity.
  if (gap.blockingTraveler && gap.occurrenceCount >= 3) return 'high';
  if (gap.severity === 'medium') return 'medium';
  return 'low';
}

const BUCKET_HEADER: Record<Bucket, string> = {
  critical: '## 🚨 Critical',
  high: '## ⚠️ High',
  medium: '## 🛠 Medium',
  low: '## 📦 Low',
};

const KIND_LABEL: Record<KnowledgeGapRow['kind'], string> = {
  tool_input_mismatch: 'tool input ≠ schema',
  tool_not_found: 'tool not registered',
  tool_error_unrecoverable: 'tool 4xx/5xx',
  instruction_missing: 'no slab guidance',
  env_missing: 'env / infra',
  schema_drift: 'description ≠ schema',
  runtime_constraint: 'platform foot-gun',
  other: 'other',
};

export function renderEntry(gap: KnowledgeGapRow): string {
  const lines: string[] = [];
  const tool = gap.toolName ? `\`${gap.toolName}\`` : '_(no tool)_';
  const occ = gap.occurrenceCount > 1 ? ` · ×${gap.occurrenceCount}` : '';
  const block = gap.blockingTraveler ? ' · 🚧 blocking' : '';
  lines.push(`### ${tool} — ${KIND_LABEL[gap.kind]}${occ}${block}`);
  lines.push('');
  lines.push(`> ${gap.hypothesis.replace(/\n/g, ' ')}`);
  lines.push('');
  if (gap.suggestedFix) {
    lines.push(`**Suggested fix:** ${gap.suggestedFix.replace(/\n/g, ' ')}`);
    lines.push('');
  }
  const ageHours = Math.floor((Date.now() - gap.firstSeenAt.getTime()) / 3_600_000);
  const lastHours = Math.floor((Date.now() - gap.lastSeenAt.getTime()) / 3_600_000);
  const meta: string[] = [
    `id: \`${gap.id}\``,
    `tenant: \`${gap.tenantId.slice(0, 12)}…\``,
    `severity: ${gap.severity}`,
    `first seen: ${ageHours}h ago`,
    `last seen: ${lastHours}h ago`,
  ];
  if (gap.surface) meta.push(`surface: ${gap.surface}`);
  if (gap.channelKind) meta.push(`channel: ${gap.channelKind}`);
  if (gap.traceId) meta.push(`trace: \`${gap.traceId}\``);
  lines.push(`<sub>${meta.join(' · ')}</sub>`);
  lines.push('');
  if (gap.errorMessage) {
    lines.push('<details><summary>Error</summary>');
    lines.push('');
    lines.push('```');
    lines.push(gap.errorMessage.slice(0, 800));
    lines.push('```');
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }
  return lines.join('\n');
}

export function renderBoard(args: {
  open: KnowledgeGapRow[];
  recentlyResolved: KnowledgeGapRow[];
  generatedAt: Date;
  resolveStaleDays: number | null;
  resolvedThisRun: KnowledgeGapRow[];
}): string {
  const buckets: Record<Bucket, KnowledgeGapRow[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
  };
  for (const g of args.open) buckets[bucket(g)].push(g);
  for (const k of Object.keys(buckets) as Bucket[]) {
    buckets[k].sort((a, b) => b.lastSeenAt.getTime() - a.lastSeenAt.getTime());
  }

  const lines: string[] = [];
  lines.push('# Sendero — agent knowledge gap board');
  lines.push('');
  lines.push(
    'Auto-generated by `bun gaps:scan` from `KnowledgeGap` rows the agent self-reports via `report_knowledge_gap` (dev/sandbox mode only).'
  );
  lines.push('');
  const total = args.open.length;
  const blocking = args.open.filter(g => g.blockingTraveler).length;
  lines.push(
    `**${total} open** · ${blocking} blocking traveler · ${args.recentlyResolved.length} resolved last 14d`
  );
  lines.push('');
  lines.push(`<sub>Generated ${args.generatedAt.toISOString()}</sub>`);
  lines.push('');

  if (args.resolveStaleDays !== null) {
    lines.push(
      `> Auto-resolve threshold: ${args.resolveStaleDays}d (rows not seen since are marked resolved).`
    );
    if (args.resolvedThisRun.length > 0) {
      lines.push('');
      lines.push(`> This run auto-resolved ${args.resolvedThisRun.length} stale rows.`);
    }
    lines.push('');
  }

  for (const b of ['critical', 'high', 'medium', 'low'] as Bucket[]) {
    if (buckets[b].length === 0) continue;
    lines.push(BUCKET_HEADER[b]);
    lines.push('');
    for (const g of buckets[b]) lines.push(renderEntry(g));
    lines.push('');
  }

  if (total === 0) {
    lines.push('## 🎉 No open gaps');
    lines.push('');
    lines.push(
      'Either the agent has everything it needs, or no one is exercising it. Run regression to disambiguate (`bun langfuse:regression`).'
    );
    lines.push('');
  }

  if (args.recentlyResolved.length > 0) {
    lines.push('## ✅ Recently resolved');
    lines.push('');
    for (const g of args.recentlyResolved.slice(0, 20)) {
      const tool = g.toolName ? `\`${g.toolName}\`` : '_(no tool)_';
      const note = g.resolutionNote ? ` — ${g.resolutionNote}` : '';
      const pr = g.resolutionPrUrl ? ` ([PR](${g.resolutionPrUrl}))` : '';
      lines.push(
        `- ${tool} · ${KIND_LABEL[g.kind]} · resolved ${g.resolvedAt?.toISOString().slice(0, 10)}${pr}${note}`
      );
    }
  }

  return lines.join('\n').trimEnd() + '\n';
}

// ── CLI arg parsing (no DB deps either) ──────────────────────────────

export interface CliArgs {
  tenant: string | null;
  since: Date;
  resolveStaleDays: number | null;
  outputPath: string;
  dryRun: boolean;
}

export function parseArgs(argv: string[], defaultOutputPath: string): CliArgs {
  const get = (flag: string): string | null => {
    const i = argv.indexOf(flag);
    return i >= 0 && i + 1 < argv.length ? argv[i + 1] : null;
  };
  const has = (flag: string): boolean => argv.includes(flag);

  const sinceStr = get('--since');
  const since = sinceStr ? new Date(sinceStr) : new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  if (Number.isNaN(since.getTime())) {
    throw new Error(`--since: invalid date "${sinceStr}". Use YYYY-MM-DD.`);
  }

  const resolveStr = get('--resolve-stale-days');
  const resolveStaleDays = resolveStr ? Number.parseInt(resolveStr, 10) : null;
  if (resolveStaleDays !== null && (!Number.isFinite(resolveStaleDays) || resolveStaleDays < 1)) {
    throw new Error(`--resolve-stale-days: must be a positive integer.`);
  }

  return {
    tenant: get('--tenant'),
    since,
    resolveStaleDays,
    outputPath: get('--output') ?? defaultOutputPath,
    dryRun: has('--dry-run'),
  };
}
