/**
 * MSCA plugin addresses — re-exported from the package's constants module.
 *
 * Ported from desk-v1 (Fantasmita LLC, internal reuse for Sendero).
 */
export {
  ADDRESS_BOOK_MANIFEST_HASH,
  ADDRESS_BOOK_PLUGIN_ADDRESS as ADDRESS_BOOK_MODULE_ADDRESS,
  WEIGHTED_WEBAUTHN_MULTISIG_MANIFEST_HASH as WEIGHTED_WEB_AUTHN_MULTISIG_PLUGIN_MANIFEST_HASH,
  WEIGHTED_WEBAUTHN_MULTISIG_OWNER_FUNCTION_ID as WEIGHTED_WEB_AUTHN_MULTISIG_OWNER_FUNCTION_ID,
  WEIGHTED_WEBAUTHN_MULTISIG_PLUGIN_ADDRESS as WEIGHTED_WEB_AUTHN_MULTISIG_PLUGIN_ADDRESS,
} from '../constants';
